-- Quality Rules table for Quality Agent
-- Stores generated and user-defined data quality rules

CREATE TABLE IF NOT EXISTS amygdala.quality_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    rule_type TEXT NOT NULL CHECK (rule_type IN ('null_check', 'range_check', 'pattern_check', 'uniqueness', 'referential', 'custom')),
    target_asset TEXT NOT NULL,
    target_column TEXT,
    expression TEXT NOT NULL,
    threshold NUMERIC NOT NULL DEFAULT 95,
    severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    enabled BOOLEAN NOT NULL DEFAULT true,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'system',

    -- Unique constraint to prevent duplicate rules
    UNIQUE(name)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_quality_rules_target_asset ON amygdala.quality_rules(target_asset);
CREATE INDEX IF NOT EXISTS idx_quality_rules_enabled ON amygdala.quality_rules(enabled) WHERE enabled = true;

-- Add issue_type 'low_trust' to issues table if not exists
DO $$
BEGIN
    -- Check if the constraint exists and update it
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'issues_issue_type_check'
    ) THEN
        ALTER TABLE amygdala.issues DROP CONSTRAINT issues_issue_type_check;
    END IF;

    ALTER TABLE amygdala.issues ADD CONSTRAINT issues_issue_type_check
        CHECK (issue_type IN ('anomaly', 'quality_failure', 'missing_data', 'freshness', 'ownership_missing', 'missing_reference', 'low_trust'));
EXCEPTION
    WHEN others THEN
        -- Constraint might not exist or already be correct
        NULL;
END $$;

-- Grant permissions
GRANT ALL ON amygdala.quality_rules TO authenticated;
GRANT ALL ON amygdala.quality_rules TO anon;
GRANT ALL ON amygdala.quality_rules TO service_role;

COMMENT ON TABLE amygdala.quality_rules IS 'Data quality rules generated by Quality Agent or defined by users';
COMMENT ON COLUMN amygdala.quality_rules.rule_type IS 'Type of validation: null_check, range_check, pattern_check, uniqueness, referential, custom';
COMMENT ON COLUMN amygdala.quality_rules.threshold IS 'Percentage of records that must pass (e.g., 95 = 95% must pass)';
COMMENT ON COLUMN amygdala.quality_rules.expression IS 'SQL expression or regex pattern for validation';
