-- ============================================
-- TRANSFORMATION AGENT TABLES
-- ============================================
-- Supports self-improving transformation loop with approval workflow

-- Transformation plans (pending or executed transformations)
CREATE TABLE amygdala.transformation_plans (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,

    -- Source of the transformation request
    source_type TEXT NOT NULL CHECK (source_type IN ('issue', 'quality_rule', 'manual', 'chat', 'agent')),
    source_id TEXT,                           -- Reference to issue, rule, or other source

    -- Target
    target_asset TEXT NOT NULL,               -- Asset name (e.g., silver_customers)
    target_column TEXT,                       -- Optional: specific column

    -- Transformation details
    transformation_type TEXT NOT NULL CHECK (transformation_type IN (
        'format_standardization',
        'null_remediation',
        'referential_fix',
        'deduplication',
        'outlier_correction',
        'classification',
        'custom_sql'
    )),
    description TEXT NOT NULL,                -- Human-readable description
    parameters JSONB DEFAULT '{}',            -- Type-specific parameters

    -- Generated code
    generated_code TEXT,                      -- Python/SQL code generated by Claude
    rollback_code TEXT,                       -- Code to undo the transformation

    -- Metadata
    affected_columns TEXT[] DEFAULT '{}',
    estimated_rows INTEGER,
    risk_level TEXT DEFAULT 'medium' CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),

    -- Iteration tracking
    iteration_count INTEGER DEFAULT 0,
    max_iterations INTEGER DEFAULT 5,
    final_accuracy DECIMAL(5,4),              -- Accuracy achieved after iterations
    accuracy_threshold DECIMAL(5,4) DEFAULT 0.95,

    -- Status
    status TEXT DEFAULT 'draft' CHECK (status IN (
        'draft',                              -- Initial creation
        'iterating',                          -- Self-improving loop in progress
        'pending_approval',                   -- Ready for human review
        'approved',                           -- Approved, waiting to execute
        'executing',                          -- Currently running
        'completed',                          -- Successfully executed
        'failed',                             -- Execution failed
        'rejected',                           -- Human rejected
        'cancelled'                           -- Cancelled by user
    )),

    -- Audit
    requested_by TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transformation iterations (self-improving loop history)
CREATE TABLE amygdala.transformation_iterations (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    plan_id TEXT REFERENCES amygdala.transformation_plans(id) ON DELETE CASCADE,

    iteration_number INTEGER NOT NULL,

    -- Generated code for this iteration
    code TEXT NOT NULL,

    -- Execution results
    executed_at TIMESTAMPTZ DEFAULT NOW(),
    execution_time_ms INTEGER,
    sample_size INTEGER,                      -- Number of rows tested

    -- Results
    success BOOLEAN DEFAULT false,
    output JSONB DEFAULT '{}',                -- Raw output from sandbox
    error_message TEXT,

    -- Evaluation
    accuracy DECIMAL(5,4),
    meets_threshold BOOLEAN DEFAULT false,
    evaluation_notes TEXT,                    -- Claude's analysis
    issues_found TEXT[] DEFAULT '{}',         -- Problems identified
    improvements_suggested TEXT[] DEFAULT '{}', -- How to improve

    -- Sample data
    sample_before JSONB DEFAULT '[]',         -- Sample rows before transformation
    sample_after JSONB DEFAULT '[]',          -- Sample rows after transformation

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transformation approvals
CREATE TABLE amygdala.transformation_approvals (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    plan_id TEXT REFERENCES amygdala.transformation_plans(id) ON DELETE CASCADE,

    -- Approval details
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
    reviewed_by TEXT,
    reviewed_at TIMESTAMPTZ,
    comment TEXT,

    -- Auto-approval
    auto_approved BOOLEAN DEFAULT false,
    auto_approve_reason TEXT,                 -- Why it was auto-approved

    -- Expiration
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '24 hours'),

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transformation execution logs
CREATE TABLE amygdala.transformation_logs (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    plan_id TEXT REFERENCES amygdala.transformation_plans(id) ON DELETE CASCADE,
    approval_id TEXT REFERENCES amygdala.transformation_approvals(id) ON DELETE SET NULL,

    -- Execution details
    snapshot_id TEXT,                         -- Reference to pre-transformation snapshot
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    duration_ms INTEGER,

    -- Results
    rows_affected INTEGER,
    rows_succeeded INTEGER,
    rows_failed INTEGER,

    -- Status
    status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'rolled_back')),
    error_message TEXT,

    -- Audit
    executed_by TEXT NOT NULL,

    -- Lineage
    lineage_recorded BOOLEAN DEFAULT false
);

-- Transformation snapshots (for rollback capability)
CREATE TABLE amygdala.transformation_snapshots (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    plan_id TEXT REFERENCES amygdala.transformation_plans(id) ON DELETE CASCADE,
    log_id TEXT REFERENCES amygdala.transformation_logs(id) ON DELETE SET NULL,

    -- What was snapshotted
    target_asset TEXT NOT NULL,
    target_column TEXT,

    -- Snapshot data
    affected_row_ids TEXT[] DEFAULT '{}',     -- IDs of rows that were changed
    snapshot_data JSONB NOT NULL,             -- Full row data before change
    row_count INTEGER,

    -- Lifecycle
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days'),

    -- Status
    used_for_rollback BOOLEAN DEFAULT false,
    rolled_back_at TIMESTAMPTZ
);

-- Indexes for performance
CREATE INDEX idx_transformation_plans_status ON amygdala.transformation_plans(status);
CREATE INDEX idx_transformation_plans_source ON amygdala.transformation_plans(source_type, source_id);
CREATE INDEX idx_transformation_plans_asset ON amygdala.transformation_plans(target_asset);
CREATE INDEX idx_transformation_plans_created ON amygdala.transformation_plans(created_at DESC);

CREATE INDEX idx_transformation_iterations_plan ON amygdala.transformation_iterations(plan_id);
CREATE INDEX idx_transformation_iterations_number ON amygdala.transformation_iterations(plan_id, iteration_number);

CREATE INDEX idx_transformation_approvals_plan ON amygdala.transformation_approvals(plan_id);
CREATE INDEX idx_transformation_approvals_status ON amygdala.transformation_approvals(status);
CREATE INDEX idx_transformation_approvals_expires ON amygdala.transformation_approvals(expires_at) WHERE status = 'pending';

CREATE INDEX idx_transformation_logs_plan ON amygdala.transformation_logs(plan_id);
CREATE INDEX idx_transformation_logs_status ON amygdala.transformation_logs(status);

CREATE INDEX idx_transformation_snapshots_plan ON amygdala.transformation_snapshots(plan_id);
CREATE INDEX idx_transformation_snapshots_expires ON amygdala.transformation_snapshots(expires_at);

-- Enable RLS
ALTER TABLE amygdala.transformation_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE amygdala.transformation_iterations ENABLE ROW LEVEL SECURITY;
ALTER TABLE amygdala.transformation_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE amygdala.transformation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE amygdala.transformation_snapshots ENABLE ROW LEVEL SECURITY;

-- Policies (allow all for now)
CREATE POLICY "Allow all access to transformation_plans" ON amygdala.transformation_plans FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transformation_iterations" ON amygdala.transformation_iterations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transformation_approvals" ON amygdala.transformation_approvals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transformation_logs" ON amygdala.transformation_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transformation_snapshots" ON amygdala.transformation_snapshots FOR ALL USING (true) WITH CHECK (true);

-- Updated_at trigger for transformation_plans
CREATE TRIGGER update_transformation_plans_updated_at
    BEFORE UPDATE ON amygdala.transformation_plans
    FOR EACH ROW
    EXECUTE FUNCTION amygdala.update_updated_at();

-- Add issue_type for transformations
ALTER TABLE amygdala.issues
DROP CONSTRAINT IF EXISTS issues_issue_type_check;

ALTER TABLE amygdala.issues
ADD CONSTRAINT issues_issue_type_check
CHECK (issue_type IN (
    'anomaly',
    'quality_failure',
    'pipeline_failure',
    'missing_data',
    'missing_reference',
    'ownership_missing',
    'freshness',
    'low_trust',
    'transformation_failed'  -- New type for failed transformations
));

-- Function to auto-expire pending approvals
CREATE OR REPLACE FUNCTION amygdala.expire_pending_approvals()
RETURNS void AS $$
BEGIN
    UPDATE amygdala.transformation_approvals
    SET status = 'expired'
    WHERE status = 'pending' AND expires_at < NOW();

    -- Also update the corresponding plans
    UPDATE amygdala.transformation_plans
    SET status = 'cancelled'
    WHERE id IN (
        SELECT plan_id FROM amygdala.transformation_approvals
        WHERE status = 'expired'
    ) AND status = 'pending_approval';
END;
$$ LANGUAGE plpgsql;

-- Function to clean up old snapshots
CREATE OR REPLACE FUNCTION amygdala.cleanup_old_snapshots()
RETURNS void AS $$
BEGIN
    DELETE FROM amygdala.transformation_snapshots
    WHERE expires_at < NOW() AND used_for_rollback = false;
END;
$$ LANGUAGE plpgsql;
